name: Titans Uptime CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore Titans.Uptime.sln

      - name: Build solution
        run: dotnet build Titans.Uptime.sln --configuration Release --no-restore

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore Titans.Uptime.sln

      - name: Build solution
        run: dotnet build Titans.Uptime.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test Titans.Uptime.sln --configuration Release --no-build --verbosity normal

  publish:
    name: Publish Artifacts
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore Titans.Uptime.sln

      - name: Publish
        run: |
          dotnet publish Titans.Uptime.Api/Titans.Uptime.Api.csproj -c Release -o publish

      - name: Upload published artifact
        uses: actions/upload-artifact@v4
        with:
          name: publish-artifact
          path: publish

  docker:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: publish
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/uptime-back:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/uptime-back:latest

  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: docker
    if: github.event_name == 'push'

    steps:
      - name: Deploy to Render
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}

